import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import Container from 'react-bootstrap/Container';
import Header from "@/components/Header";
import NextAuthProvider from "@/providers/NextAuthProvider";
import GlobalProvider from "@/providers/GlobalProvider";
import AxiosInterceptor from "@/providers/AxiosInterceptor";



import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />

        <NextAuthProvider>
          <GlobalProvider>
            <AxiosInterceptor>
              <Header />
              <Container>
                {children}
              </Container>
            </AxiosInterceptor>
          </GlobalProvider>
        </NextAuthProvider>

      </body>
    </html>
  );
}
